### ISSUE TITLE
Does not seem to work with Taskwarrior 2.6

### ISSUE THREAD

**Issue by duckunix** [thehunmonkgroup/onenote#2]
It seems that something has changed from 2.5.x to 2.6.0.  Under 2.5.x, the normal behavior happens, but under 2.6, when running '''onenote''', where there should be line feed, is says '''###NEWLINE###'''.  

I do have the hooks in place, and it works find if I revert back to 2.5.3.

**Comment by thehunmonkgroup** [comment]
https://github.com/thehunmonkgroup/onenote#caveats
